version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - AWS_ACCESS_KEY_ID=your_access_key_id
      - AWS_SECRET_ACCESS_KEY=your_secret_access_key
      - AWS_REGION=your_aws_region
      - AWS_S3_BUCKET_NAME=your_s3_bucket_name
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/musicplayer
      - SPRING_DATASOURCE_USERNAME=your_db_username
      - SPRING_DATASOURCE_PASSWORD=your_db_password
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: your_db_username
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: musicplayer
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
